title: Road To Dev
author: MarijnSt
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  I'm heading in a new direction and want to become a webdev. 
  This time it's for real and I hope to be a competent web coder in the coming months!

# social links
twitter_username: your-twitter-handle
github_username:  your-github-handle

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
